import { useCallback, useEffect, useMemo, useState } from "react";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { useLocalSearchParams } from "expo-router";
import { AppIcon } from "@/src/components/AppIcon";
import { getCoachClientNutritionPlan, listCoachCheckins, listCoachNutritionCheckins } from "@/src/api/supabase";
import { hasSupabaseEnv } from "@/src/constants/env";
import { calculateNutritionAdherence } from "@/src/domain/nutrition";
import { useTheme } from "@/src/hooks";
import type { CoachCheckin, CoachNutritionPlan, NutritionCheckin } from "@/src/types";
import { WebShell } from "./WebChrome";
function dateLabel(value?: string) { if (!value) return "—"; const [y,m,d] = value.split("-"); return y && m && d ? `${d}/${m}/${y}` : value; }
function daysAgo(value: string) { const date = new Date(`${value}T00:00:00`).getTime(); return Number.isFinite(date) ? Math.max(0, Math.floor((Date.now() - date) / 86400000)) : 999; }
export function WebCoachAdherenceScreen() {
  const params = useLocalSearchParams<{ clientId?: string; clientName?: string }>();
  const clientId = typeof params.clientId === "string" ? params.clientId : "";
  const clientName = typeof params.clientName === "string" ? params.clientName : "Aluno VRTX";
  const { colors } = useTheme();
  const [checkins, setCheckins] = useState<CoachCheckin[]>([]);
  const [nutritionCheckins, setNutritionCheckins] = useState<NutritionCheckin[]>([]);
  const [plan, setPlan] = useState<CoachNutritionPlan | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const online = hasSupabaseEnv();
  const load = useCallback(async () => {
    if (!clientId || !online) { setLoading(false); return; }
    setLoading(true); setError(null);
    const [workouts, meals, nutrition] = await Promise.all([listCoachCheckins(clientId), listCoachNutritionCheckins(clientId), getCoachClientNutritionPlan(clientId)]);
    setCheckins(workouts.data ?? []); setNutritionCheckins(meals.data ?? []); setPlan(nutrition.data ?? null);
    setError(workouts.error ?? meals.error ?? nutrition.error ?? null); setLoading(false);
  }, [clientId, online]);
  useEffect(() => { void load(); }, [load]);
  const week = useMemo(() => checkins.filter((item) => daysAgo(item.happenedOn) <= 7), [checkins]);
  const volume = week.reduce((sum, item) => sum + item.totalVolume, 0);
  const nutritionRate = useMemo(() => {
    const mealsPerDay = (plan?.meals ?? []).filter((meal) => meal.items.length > 0).length;
    if (!mealsPerDay) return null;
    return calculateNutritionAdherence(mealsPerDay, nutritionCheckins.filter((item) => daysAgo(item.happenedOn) <= 7), 7);
  }, [nutritionCheckins, plan]);
  return <WebShell backRoute="/students" eyebrow="Aderência do aluno" title={clientName}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.scroll}>
    <View style={[styles.hero, { backgroundColor: colors.primary + "12", borderColor: colors.primary + "45" }]}><View style={styles.heroCopy}><Text style={[styles.eyebrow, { color: colors.primary }]}>WEEKLY SIGNAL</Text><Text style={[styles.heroTitle, { color: colors.foreground }]}>Consistência que dá para acompanhar.</Text><Text style={[styles.heroText, { color: colors.foregroundMuted }]}>Veja se o aluno está executando o plano e onde o coach pode agir agora.</Text></View><View style={[styles.score, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.scoreValue, { color: colors.foreground }]}>{week.length}</Text><Text style={[styles.scoreLabel, { color: colors.muted }]}>sessões na semana</Text></View></View>
    {!online ? <Notice text="Modo demonstração: conecte o Supabase para carregar check-ins." color={colors.warning} /> : null}{error ? <Notice text={error} color={colors.error} /> : null}
    <View style={styles.metrics}><Metric label="SESSÕES" value={String(week.length)} hint="últimos 7 dias" colors={colors} icon="Dumbbell" /><Metric label="VOLUME" value={`${Math.round(volume)} kg`} hint="registrado na semana" colors={colors} icon="TrendingUp" /><Metric label="ÚLTIMO TREINO" value={checkins[0] ? dateLabel(checkins[0].happenedOn) : "—"} hint={checkins[0]?.workoutName ?? "sem registro"} colors={colors} icon="Clock" /><Metric label="NUTRIÇÃO" value={nutritionRate ? `${Math.round(nutritionRate.rate * 100)}%` : "—"} hint={nutritionRate ? "refeições seguidas" : "sem plano ativo"} colors={colors} icon="Apple" /></View>
    <View style={styles.columns}><View style={[styles.panel, { backgroundColor: colors.surface, borderColor: colors.border }]}><PanelHeader eyebrow="TREINOS" title="Histórico de sessões" colors={colors} />{loading ? <Empty text="Carregando check-ins..." colors={colors} /> : checkins.length === 0 ? <Empty text="Nenhuma sessão registrada ainda." colors={colors} /> : checkins.slice(0, 12).map((item) => <View key={item.id} style={[styles.row, { borderTopColor: colors.border }]}><View style={[styles.rowIcon, { backgroundColor: colors.success + "18" }]}><AppIcon name="Check" size={15} color={colors.success} /></View><View style={styles.rowCopy}><Text style={[styles.rowTitle, { color: colors.foreground }]}>{item.workoutName}</Text><Text style={[styles.rowMeta, { color: colors.muted }]}>{dateLabel(item.happenedOn)} · {item.exerciseCount} exercícios · {item.setCount} séries</Text></View><Text style={[styles.rowValue, { color: colors.primary }]}>{Math.round(item.totalVolume)} kg</Text></View>)}</View><View style={[styles.panel, { backgroundColor: colors.surface, borderColor: colors.border }]}><PanelHeader eyebrow="NUTRIÇÃO" title="Check-ins de refeições" colors={colors} />{nutritionRate ? <View style={[styles.nutritionCard, { backgroundColor: colors.primary + "12", borderColor: colors.primary + "35" }]}><Text style={[styles.nutritionRate, { color: colors.primary }]}>{Math.round(nutritionRate.rate * 100)}%</Text><Text style={[styles.nutritionCopy, { color: colors.foregroundMuted }]}>{nutritionRate.followedMeals} de {nutritionRate.plannedMeals} refeições planejadas foram seguidas nos últimos 7 dias.</Text></View> : <Empty text="Crie um plano nutricional para medir aderência." colors={colors} />}{nutritionCheckins.slice(0, 8).map((item) => <View key={item.id} style={[styles.row, { borderTopColor: colors.border }]}><View style={[styles.rowIcon, { backgroundColor: (item.followed ? colors.success : colors.warning) + "18" }]}><AppIcon name={item.followed ? "Check" : "Clock"} size={15} color={item.followed ? colors.success : colors.warning} /></View><View style={styles.rowCopy}><Text style={[styles.rowTitle, { color: colors.foreground }]}>{item.mealType}</Text><Text style={[styles.rowMeta, { color: colors.muted }]}>{dateLabel(item.happenedOn)} · {item.calories} kcal</Text></View><Text style={[styles.rowValue, { color: item.followed ? colors.success : colors.warning }]}>{item.followed ? "SEGUIDA" : "PENDENTE"}</Text></View>)}</View></View>
  </ScrollView></WebShell>;
}
function Notice({ text, color }: any) { return <View style={[styles.notice, { backgroundColor: color + "14", borderColor: color + "45" }]}><Text style={[styles.noticeText, { color }]}>{text}</Text></View>; }
function Metric({ label, value, hint, icon, colors }: any) { return <View style={[styles.metric, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.metricHead}><View style={[styles.metricIcon, { backgroundColor: colors.primary + "18" }]}><AppIcon name={icon} size={15} color={colors.primary} /></View><Text style={[styles.eyebrow, { color: colors.muted }]}>{label}</Text></View><Text style={[styles.metricValue, { color: colors.foreground }]}>{value}</Text><Text style={[styles.metricHint, { color: colors.muted }]}>{hint}</Text></View>; }
function PanelHeader({ eyebrow, title, colors }: any) { return <View style={styles.panelHeader}><View><Text style={[styles.eyebrow, { color: colors.muted }]}>{eyebrow}</Text><Text style={[styles.panelTitle, { color: colors.foreground }]}>{title}</Text></View><AppIcon name="BarChart" size={17} color={colors.primary} /></View>; }
function Empty({ text, colors }: any) { return <Text style={[styles.empty, { color: colors.muted }]}>{text}</Text>; }
const styles = StyleSheet.create({ scroll: { gap: 16, paddingBottom: 60 }, hero: { borderWidth: 1, borderRadius: 20, padding: 22, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 16 }, heroCopy: { flex: 1 }, eyebrow: { fontFamily: "monospace", fontSize: 9, fontWeight: "800", letterSpacing: 1.2 }, heroTitle: { fontSize: 25, lineHeight: 30, fontWeight: "900", marginTop: 7 }, heroText: { fontSize: 13, lineHeight: 20, marginTop: 8 }, score: { minWidth: 110, borderWidth: 1, borderRadius: 15, alignItems: "center", padding: 15 }, scoreValue: { fontSize: 29, fontWeight: "900" }, scoreLabel: { fontSize: 10, textAlign: "center", marginTop: 3 }, notice: { borderWidth: 1, borderRadius: 13, padding: 12 }, noticeText: { fontSize: 12, fontWeight: "700" }, metrics: { flexDirection: "row", flexWrap: "wrap", gap: 12 }, metric: { flex: 1, minWidth: 180, borderWidth: 1, borderRadius: 16, padding: 15, gap: 8 }, metricHead: { flexDirection: "row", alignItems: "center", gap: 8 }, metricIcon: { width: 28, height: 28, borderRadius: 9, alignItems: "center", justifyContent: "center" }, metricValue: { fontSize: 23, fontWeight: "900" }, metricHint: { fontSize: 11 }, columns: { flexDirection: "row", flexWrap: "wrap", gap: 16 }, panel: { flex: 1, minWidth: 360, borderWidth: 1, borderRadius: 18, padding: 19, gap: 13 }, panelHeader: { flexDirection: "row", justifyContent: "space-between" }, panelTitle: { fontSize: 18, fontWeight: "900", marginTop: 6 }, row: { minHeight: 57, borderTopWidth: 1, paddingVertical: 9, flexDirection: "row", alignItems: "center", gap: 10 }, rowIcon: { width: 30, height: 30, borderRadius: 9, alignItems: "center", justifyContent: "center" }, rowCopy: { flex: 1, gap: 3 }, rowTitle: { fontSize: 12, fontWeight: "800" }, rowMeta: { fontSize: 11 }, rowValue: { fontFamily: "monospace", fontSize: 10, fontWeight: "800" }, nutritionCard: { borderWidth: 1, borderRadius: 13, padding: 14, gap: 4 }, nutritionRate: { fontSize: 29, fontWeight: "900" }, nutritionCopy: { fontSize: 12, lineHeight: 18 }, empty: { fontSize: 13, lineHeight: 20, paddingVertical: 8 } });
