import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { WebShell } from "./WebChrome";
import { AppIcon } from "@/src/components/AppIcon";
import { useTheme } from "@/src/hooks";
import { usePremiumStore } from "@/src/store/premiumStore";

const features = ["Coach IA com contexto do seu histórico", "Relatórios de progresso mais profundos", "Treinos personalizados ilimitados", "Backup e sincronização de dados", "Recomendações de nutrição mais precisas"];
export function WebSubscriptionScreen() {
  const { colors } = useTheme();
  const { isPremium, subscriptionType, expiryDate } = usePremiumStore();
  const choosePlan = (plan: string) => Alert.alert("Plano VRTX Pro", `A próxima etapa segura de assinatura será aberta para o plano ${plan}.`);
  return <WebShell backRoute="/profile" eyebrow="VRTX Pro" title="Assinatura que acompanha sua evolução."><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.scroll}><View style={[styles.hero, { backgroundColor: colors.primary + "16", borderColor: colors.primary + "55" }]}><View style={styles.heroCopy}><Text style={[styles.kicker, { color: colors.primary }]}>MEMBRESIA VRTX</Text><Text style={[styles.heroTitle, { color: colors.foreground }]}>Mais contexto. Menos ruído.</Text><Text style={[styles.description, { color: colors.foregroundMuted }]}>Escolha o nível de suporte que faz sentido para o seu momento e mantenha o foco no que realmente muda seu corpo e sua rotina.</Text></View><View style={[styles.statusCard, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.statusLabel, { color: colors.muted }]}>SEU PLANO ATUAL</Text><Text style={[styles.statusValue, { color: colors.foreground }]}>{isPremium ? "VRTX PRO" : "PLANO GRATUITO"}</Text><Text style={[styles.statusHint, { color: colors.foregroundMuted }]}>{isPremium ? `${subscriptionType === "none" ? "Ativo" : subscriptionType} · ${expiryDate ? `até ${expiryDate.slice(0, 10)}` : "sem expiração informada"}` : "Comece quando estiver pronto"}</Text></View></View><View style={styles.plans}><PlanCard title="Essencial" price="Grátis" copy="Para criar consistência" features={["Plano do dia", "Registro de treino e refeições", "Histórico básico"]} colors={colors} current={!isPremium} onPress={() => choosePlan("Essencial")} /><PlanCard title="VRTX Pro" price="Mais completo" copy="Para evoluir com contexto" features={features} colors={colors} featured current={isPremium} onPress={() => choosePlan("VRTX Pro")} /></View><View style={[styles.note, { borderColor: colors.border, backgroundColor: colors.surface }]}><View style={[styles.noteIcon, { backgroundColor: colors.primary + "18" }]}><AppIcon name="Shield" size={18} color={colors.primary} /></View><View style={styles.noteCopy}><Text style={[styles.noteTitle, { color: colors.foreground }]}>Compra segura e transparente</Text><Text style={[styles.noteText, { color: colors.foregroundMuted }]}>Os valores finais, período de cobrança e opções de cancelamento aparecem antes da confirmação. Nada é cobrado nesta tela.</Text></View></View></ScrollView></WebShell>;
}
function PlanCard({ title, price, copy, features: items, colors, featured, current, onPress }: any) { return <View style={[styles.plan, { backgroundColor: colors.surface, borderColor: featured ? colors.primary : colors.border }, featured && { borderWidth: 2 }]}>{featured ? <View style={[styles.badge, { backgroundColor: colors.primary }]}><Text style={styles.badgeText}>RECOMENDADO</Text></View> : null}<Text style={[styles.planTitle, { color: colors.foreground }]}>{title}</Text><Text style={[styles.planPrice, { color: featured ? colors.primary : colors.foreground }]}>{price}</Text><Text style={[styles.planCopy, { color: colors.muted }]}>{copy}</Text><View style={styles.featureList}>{items.map((item: string) => <View key={item} style={styles.feature}><AppIcon name="Check" size={14} color={colors.primary} /><Text style={[styles.featureText, { color: colors.foregroundMuted }]}>{item}</Text></View>)}</View><Pressable onPress={onPress} style={[styles.planButton, { backgroundColor: featured ? colors.primary : colors.background, borderColor: featured ? colors.primary : colors.border }]}><Text style={[styles.planButtonText, { color: featured ? "#06111D" : colors.foreground }]}>{current ? "Plano atual" : featured ? "Conhecer VRTX Pro" : "Continuar no Essencial"}</Text></Pressable></View>; }
const styles = StyleSheet.create({ scroll: { paddingBottom: 60, gap: 18 }, hero: { borderWidth: 1, borderRadius: 22, padding: 26, flexDirection: "row", justifyContent: "space-between", gap: 20, flexWrap: "wrap" }, heroCopy: { flex: 1, minWidth: 280, maxWidth: 680 }, kicker: { fontFamily: "monospace", fontSize: 10, letterSpacing: 1.6, fontWeight: "800" }, heroTitle: { fontSize: 31, fontWeight: "900", letterSpacing: -1, marginTop: 8 }, description: { fontSize: 14, lineHeight: 22, marginTop: 10 }, statusCard: { minWidth: 210, borderWidth: 1, borderRadius: 15, padding: 16, justifyContent: "center", gap: 6 }, statusLabel: { fontFamily: "monospace", fontSize: 9, letterSpacing: 1.2 }, statusValue: { fontSize: 17, fontWeight: "900" }, statusHint: { fontSize: 11, lineHeight: 16 }, plans: { flexDirection: "row", gap: 16, flexWrap: "wrap" }, plan: { flex: 1, minWidth: 290, borderWidth: 1, borderRadius: 20, padding: 22, gap: 10, position: "relative" }, badge: { position: "absolute", top: -11, right: 18, borderRadius: 99, paddingHorizontal: 10, paddingVertical: 5 }, badgeText: { color: "#06111D", fontSize: 9, fontWeight: "900", letterSpacing: 0.6 }, planTitle: { fontSize: 21, fontWeight: "900" }, planPrice: { fontSize: 19, fontWeight: "900", marginTop: 4 }, planCopy: { fontSize: 12 }, featureList: { gap: 10, marginTop: 12, minHeight: 140 }, feature: { flexDirection: "row", alignItems: "flex-start", gap: 8 }, featureText: { flex: 1, fontSize: 12, lineHeight: 18 }, planButton: { minHeight: 44, borderWidth: 1, borderRadius: 11, alignItems: "center", justifyContent: "center", marginTop: 8 }, planButtonText: { fontSize: 12, fontWeight: "900" }, note: { borderWidth: 1, borderRadius: 16, padding: 16, flexDirection: "row", gap: 12 }, noteIcon: { width: 34, height: 34, borderRadius: 10, alignItems: "center", justifyContent: "center" }, noteCopy: { flex: 1, gap: 4 }, noteTitle: { fontSize: 13, fontWeight: "900" }, noteText: { fontSize: 12, lineHeight: 18 } });
